!function(){"use strict";const $=id=>document.getElementById(id);let sb,sections=[],active=null,selectedMedia=null;
function slugify(s){return(s||"section").trim().toLowerCase().replace(/[^a-z0-9\u0e00-\u0e7f]+/g,"-").replace(/^-|-$/g,"")||"section"}
function msg(text,error){$("saveStatus").textContent=text||"";$("saveStatus").style.color=error?"#b42318":""}
async function requireAdmin(){sb=window.AuthClient.sb;const user=await window.AuthClient.requireLogin();if(!user)return false;const profile=await window.AuthClient.getMyProfile();if(!profile||profile.role!=="admin"){$("accessGate").textContent="หน้านี้สำหรับ Role admin เท่านั้น";return false}$("accessGate").style.display="none";$("editorRoot").style.display="grid";return true}
async function load(){const{data,error}=await sb.from("manual_sections").select("*").order("sort_order");if(error){msg("โหลดคู่มือไม่สำเร็จ: "+error.message,true);return}sections=data||[];renderList();if(sections.length)select(sections[0].id)}
function renderList(){const list=$("sectionList");list.innerHTML=sections.map((s,i)=>`<div class="section-item ${active&&active.id===s.id?"active":""}"><button data-open="${s.id}">${escapeText(s.title)}</button><span class="section-tools"><button data-up="${s.id}" ${i===0?"disabled":""}>↑</button><button data-down="${s.id}" ${i===sections.length-1?"disabled":""}>↓</button></span></div>`).join("")||'<div class="manual-status">ยังไม่มีหัวข้อ</div>';list.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>select(b.dataset.open));list.querySelectorAll("[data-up]").forEach(b=>b.onclick=()=>move(b.dataset.up,-1));list.querySelectorAll("[data-down]").forEach(b=>b.onclick=()=>move(b.dataset.down,1))}
function escapeText(s){const d=document.createElement("div");d.textContent=s||"";return d.innerHTML}
function select(id){active=sections.find(s=>s.id===id);if(!active)return;$("sectionTitle").value=active.title||"";$("sectionPublished").value=String(active.published!==false);$("richEditor").innerHTML=active.content_html||"";chooseMedia(null);renderList();msg("")}
async function add(){const order=sections.length?Math.max(...sections.map(s=>Number(s.sort_order)||0))+1:1,{data,error}=await sb.from("manual_sections").insert({title:"หัวข้อใหม่",slug:"section-"+Date.now(),content_html:"<p>เริ่มเขียนเนื้อหาที่นี่</p>",sort_order:order,published:false}).select().single();if(error)return msg("เพิ่มหัวข้อไม่สำเร็จ: "+error.message,true);sections.push(data);select(data.id)}
async function save(){if(!active)return;msg("กำลังบันทึก...");const title=$("sectionTitle").value.trim()||"ไม่มีชื่อ",payload={title,slug:active.slug||slugify(title),content_html:$("richEditor").innerHTML,published:$("sectionPublished").value==="true",updated_at:new Date().toISOString()},{data,error}=await sb.from("manual_sections").update(payload).eq("id",active.id).select("id,title,slug,content_html,sort_order,published,updated_at");if(error)return msg("บันทึกไม่สำเร็จ: "+error.message,true);if(!Array.isArray(data)||data.length===0)return msg("บันทึกไม่สำเร็จ: ไม่พบแถวที่แก้ไข กรุณาตรวจ Policy ของ Role admin ใน Supabase",true);Object.assign(active,data[0]);renderList();msg("บันทึกแล้ว")}
async function remove(){if(!active||!confirm(`ลบหัวข้อ “${active.title}” ใช่หรือไม่?`))return;const{error}=await sb.from("manual_sections").delete().eq("id",active.id);if(error)return msg("ลบไม่สำเร็จ: "+error.message,true);sections=sections.filter(s=>s.id!==active.id);active=null;$("richEditor").innerHTML="";renderList();if(sections[0])select(sections[0].id)}
async function move(id,delta){const i=sections.findIndex(s=>s.id===id),j=i+delta;if(i<0||j<0||j>=sections.length)return;[sections[i],sections[j]]=[sections[j],sections[i]];await Promise.all(sections.map((s,index)=>sb.from("manual_sections").update({sort_order:index+1}).eq("id",s.id)));renderList()}
function command(cmd,value){$("richEditor").focus();document.execCommand(cmd,false,value||null)}
function insertHtml(html){$("richEditor").focus();document.execCommand("insertHTML",false,html)}
function youtubeId(url){const m=String(url||"").match(/(?:youtu\.be\/|youtube(?:-nocookie)?\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/i);return m&&m[1]}
async function uploadImage(file){if(!file)return;msg("กำลังอัปโหลดรูป...");const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,""),path=`manual/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`,{error}=await sb.storage.from("manual-media").upload(path,file,{cacheControl:"3600",upsert:false});if(error)return msg("อัปโหลดรูปไม่สำเร็จ: "+error.message,true);const{data}=sb.storage.from("manual-media").getPublicUrl(path);insertHtml(`<div class="media-block align-center" style="width:75%" contenteditable="false"><img src="${data.publicUrl}" alt="ภาพประกอบคู่มือ"></div><p><br></p>`);msg("เพิ่มรูปแล้ว")}
function mediaWidth(el){const value=parseFloat(el&&el.style.width);return Number.isFinite(value)?Math.max(10,Math.min(100,value)):100}
function applyMediaWidth(value){if(!selectedMedia)return;const width=Math.max(10,Math.min(100,Number(value)||100));selectedMedia.style.width=width+"%";selectedMedia.style.maxWidth="100%";const slider=$("mediaSizeRange"),label=$("mediaSizeValue");if(slider)slider.value=String(width);if(label)label.textContent=width+"%"}
function ensureMediaSlider(){if($("mediaSizeRange"))return;const controls=$("mediaControls"),anchor=controls.querySelector("[data-width]"),slider=document.createElement("input"),label=document.createElement("strong");slider.type="range";slider.id="mediaSizeRange";slider.min="10";slider.max="100";slider.step="1";slider.value="100";slider.title="เลื่อนเพื่อปรับขนาดรูปหรือวิดีโอ";label.id="mediaSizeValue";label.textContent="100%";slider.oninput=()=>applyMediaWidth(slider.value);controls.insertBefore(slider,anchor);controls.insertBefore(label,anchor)}
function chooseMedia(el){ensureMediaSlider();$("richEditor").querySelectorAll(".selected").forEach(x=>x.classList.remove("selected"));selectedMedia=null;if(el){selectedMedia=el.closest(".media-block");if(!selectedMedia&&el.tagName==="IMG")selectedMedia=el;if(!selectedMedia&&el.tagName==="IFRAME")selectedMedia=el.closest(".video-frame")||el}$("mediaControls").classList.toggle("show",!!selectedMedia);if(selectedMedia){selectedMedia.classList.add("selected");applyMediaWidth(mediaWidth(selectedMedia))}}
function bind(){$("btnAddSection").onclick=add;$("btnSaveSection").onclick=save;$("btnDeleteSection").onclick=remove;$("toolbar").querySelectorAll("[data-cmd]").forEach(el=>{const event=el.tagName==="SELECT"?"change":"click";el.addEventListener(event,()=>command(el.dataset.cmd,el.value))});$("btnLink").onclick=()=>{const url=prompt("วาง URL ที่ต้องการเชื่อมโยง");if(url)command("createLink",url)};$("btnImage").onclick=()=>$("imageInput").click();$("imageInput").onchange=e=>uploadImage(e.target.files[0]);$("btnYoutube").onclick=()=>{const raw=prompt("วางลิงก์ YouTube"),id=youtubeId(raw);if(!raw)return;if(!id)return alert("ลิงก์ YouTube ไม่ถูกต้อง");insertHtml(`<div class="media-block align-center" style="width:100%" contenteditable="false"><div class="video-frame"><iframe src="https://www.youtube-nocookie.com/embed/${id}?rel=0&playsinline=1" title="YouTube video" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen" allowfullscreen></iframe></div></div><p><br></p>`)};$("richEditor").onclick=e=>chooseMedia(e.target);$("mediaControls").querySelectorAll("[data-width]").forEach(b=>b.onclick=()=>selectedMedia&&(selectedMedia.style.width=b.dataset.width+"%"));$("mediaControls").querySelectorAll("[data-align]").forEach(b=>b.onclick=()=>{if(!selectedMedia)return;selectedMedia.classList.remove("align-left","align-center","align-right");selectedMedia.classList.add("align-"+b.dataset.align)});$("btnRemoveMedia").onclick=()=>{if(selectedMedia){selectedMedia.remove();chooseMedia(null)}}}
document.addEventListener("click",event=>{const widthButton=event.target.closest("[data-width]"),alignButton=event.target.closest("[data-align]");if(widthButton&&selectedMedia)applyMediaWidth(widthButton.dataset.width);if(alignButton&&selectedMedia){selectedMedia.style.display="block";selectedMedia.style.marginLeft=alignButton.dataset.align==="left"?"0":"auto";selectedMedia.style.marginRight=alignButton.dataset.align==="right"?"0":"auto"}});
!async function(){if(await requireAdmin()){bind();await load()}}()}();
